version: '3.3'

services:
  db:
    image: db_automation
    build:
      context: ..
      dockerfile: windows/db.Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    build:
      context: ..
      dockerfile: windows/wp.Dockerfile
    depends_on:
      - db
    image: wp_automation
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
